# Generated by Django 5.2 on 2025-04-07 23:40

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinguisticAPIProvider',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('codename', models.CharField(max_length=75, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Linguistic API Provider',
                'verbose_name_plural': 'Linguistic API Providers',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=75, unique=True)),
                ('codename', models.CharField(max_length=75, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('word', apps.core.models.LowercaseCharField(db_index=True, max_length=255, unique=True)),
                ('part_of_speech', models.CharField(blank=True, max_length=50, null=True)),
                ('definition', models.TextField(blank=True, null=True)),
                ('examples', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('familiarity_score', models.PositiveIntegerField(default=0)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to='words.word')),
            ],
            options={
                'verbose_name': 'User Word',
                'verbose_name_plural': 'User Words',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
