# Generated by Django 5.2 on 2025-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts_audio'),
        ),
    ]
