# Generated by Django 5.2 on 2026-01-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tts_audio/'),
        ),
    ]
